server:
  port: 8005
# 日志配置
logging:
  level:
    com.health: debug
    org.springframework: warn
spring:
  profiles:
    active: dev
    # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: redis2017ylz     # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

feign:
  hystrix:
    enabled: true

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
