server:
  port: 8082
# 日志配置
logging:
  level:
    com.health: debug
    org.springframework: warn
spring:
  profiles:
    active: @profileActive@
  devtools:
    restart:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      maxFileSize: 5MB  #单位必须大写MB或不写(即为B)
      maxRequestSize: 10MB
  # 数据库版本管理工具
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true


feign:
  hystrix:
    enabled: true
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# MyBatis
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.health.system.domain,com.health.system.domain.dto
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: com/health/system/mapper/xml/*.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
