server:
  port: 8081

spring:
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: redis2017ylz     # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      # 认证中心
      - id: health-auth
        uri: lb://health-auth
        predicates:
        - Path=/auth/**
        filters:
        # 验证码处理
        - CacheRequest
        - ImgCodeFilter
        - StripPrefix=1
      # 代码生成
      - id: health-gen
        uri: lb://health-gen
        predicates:
        - Path=/gen/**
        filters:
        - StripPrefix=1
      # dfs
      - id: health-dfs
        uri: lb://health-dfs
        predicates:
        - Path=/dfs/**
        filters:
        - StripPrefix=1
      # act
      - id: health-activiti
        uri: lb://health-activiti
        predicates:
        - Path=/act/**
        filters:
        - StripPrefix=1
      #system 模块
      - id: health-system
        uri: lb://health-system
        predicates:
        - Path=/system/**
        filters:
        # 限流配置
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@remoteAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
          # 降级配置
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: 'forward:/fallback'

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8080/eureka/
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

