server:
  port: 8081

spring:
  profiles:
    active: @profileActive@
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      # 认证中心
      - id: health-auth
        uri: lb://health-auth
        predicates:
        - Path=/auth/**
        filters:
        # 验证码处理
        - CacheRequest
        - ImgCodeFilter
        - StripPrefix=1
      #system 模块
      - id: health-system
        uri: lb://health-system
        predicates:
        - Path=/system/**
        filters:
        # 限流配置
        - StripPrefix=1
#        - name: RequestRateLimiter
#          args:
#            key-resolver: '#{@remoteAddrKeyResolver}'
#            redis-rate-limiter.replenishRate: 10
#            redis-rate-limiter.burstCapacity: 20
          # 降级配置
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: 'forward:/fallback'

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #断路器超时时间，默认1000ms
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

